const searchForm = document.querySelector('#search-form')
const searchTermInput = document.querySelector('#search-term')
const searchTypeInput = document.querySelector('#search-type')
const searchYearInput = document.querySelector('#search-year')
const searchSubmitBtn = document.querySelector('#submit-btn')
const dataContainer = document.querySelector('#data-container')